[tool.black]
line-length = 88
target-version = ["py311"]

[tool.pylint.format]
max-line-length = "88"

[tool.isort]
profile = "black"

[tools.pyright]
reportMissingTypeArgument = true
strictListInference = true